[book]
title = "My ZHAW Notes"
authors = [ "Janis Huser" ]
language = "de"

[rust]
edition = "2018"

[output.html]
mathjax-support = false
site-url = "/ZHAW-Informatik/"
git-repository-url = "https://github.com/schnre/ZHAW-Informatik/tree/main"
edit-url-template = "https://github.com/schnre/ZHAW-Informatik/tree/main/{path}"
additional-js = ["pyscript.js", "load-py-modules.js"]

[output.html.playground]
editable = true         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = true          # displays a run button for rust code


[output.html.code.hidelines]
python = "~"


[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding


[preprocessor.katex]
after = ["links"]
# KaTeX options.
output = "html"
leqno = false
fleqn = false
throw-on-error = true
error-color = "#cc0000"
min-rule-thickness = -1.0
max-size = "Infinity"
max-expand = 1000
trust = false
# Extra options.
no-css = false
include-src = false
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }



[preprocessor.python]
command = "mdbook-python"

[output.html.print]
enable = true    # include support for printable output
page-break = false # insert page-break after each chapter